# Generated by Django 2.2.12 on 2020-04-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200425_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='prefecture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
