# Generated by Django 2.2.12 on 2020-04-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
    ]
