# Generated by Django 2.2.12 on 2020-04-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_brewery_prefecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='breweries'),
        ),
    ]
