# Generated by Django 2.2.12 on 2020-04-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200426_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Brewery'),
        ),
    ]
