# Generated by Django 2.2.12 on 2020-04-21 14:24

from django.db import migrations, models
import main.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200421_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product_name',
            field=models.CharField(default=main.models.product.Product, max_length=50),
        ),
    ]
