# Generated by Django 2.2.12 on 2020-04-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productimage_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_name',
        ),
    ]
