# Generated by Django 2.2.12 on 2020-04-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200427_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartlines', to='main.Cart'),
        ),
    ]
