# Generated by Django 2.2.12 on 2020-04-21 14:28

from django.db import migrations, models
import main.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_productimage_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='associated_product_name',
            field=models.CharField(default=main.models.product.Product, max_length=50),
        ),
    ]
