# Generated by Django 2.2.12 on 2020-04-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productimage_associated_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='associated_product_name',
        ),
    ]
