# Generated by Django 2.2.12 on 2020-04-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(to='main.UserProfile'),
        ),
    ]
