# Generated by Django 2.2.12 on 2020-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lede',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
