# Generated by Django 2.2.12 on 2020-05-03 15:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_post_lede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='header',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_image'),
        ),
    ]
